# Base image
FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Arguments for secrets (to match pipeline's build-args)
ARG SECRET_KEY
ARG DATABASE_URL
ARG GOOGLE_APPLICATION_CREDENTIALS_BASE64

# Install dependencies
COPY requirements.txt .
RUN apt-get update && apt-get install -y wget && rm -rf /var/lib/apt/lists/*
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY . .

# Add Cloud SQL Proxy
RUN wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O /cloud_sql_proxy && chmod +x /cloud_sql_proxy

# Decode and copy the service account key from the base64 argument
COPY buzzwatch-422510-fa25a0e8d442.json /secrets/
ENV GOOGLE_APPLICATION_CREDENTIALS="/secrets/buzzwatch-422510-fa25a0e8d442.json"

# Set environment variables
ENV SECRET_KEY=6640eac2136b46b05bd536bf4a9e4ba9d7d324dccc2a2e5d73692ba6eb20aab9
ENV DATABASE_URL=mysql+mysqlconnector://user:userpass@127.0.0.1:3306/userdatabase

# Expose application port
EXPOSE 8000

# Create a script to run both processes
COPY start.sh /start.sh
RUN chmod +x /start.sh

# Use the script as the entrypoint
ENTRYPOINT ["/start.sh"]
